trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.14'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-10.14'
        python.version: '3.7'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - task: DeleteFiles@1
    inputs:
      contents: 'spacy_ray'
    displayName: 'Delete source directory'

  - script: pip install dist/*.tar.gz
    displayName: 'Install from sdist'

  - script: python -m pytest --pyargs spacy_ray
    displayName: 'Run tests'
